import { ButtonCtl } from "./frame/ctl/ButtonCtl";
import { CheckBoxCtl } from "./frame/ctl/CheckBoxCtl";
import { TabControl } from "./frame/ctl/TabControl";
import { TimeCheckCtl } from "./frame/ctl/TimeCheckCtl";
import { TimeCtl } from "./frame/ctl/TimeCtl";
import { DebugUtil } from "./frame/util/DebugUtil";
import { HttpUtil } from "./frame/util/HttpUtil";
import { LayoutUtil } from "./frame/util/LayoutUtil";
import { ListUtil } from "./frame/util/ListUtil";
import { LogSys } from "./frame/util/LogSys";
import { RandomUtil } from "./frame/util/RandomUtil";
import { StringUtil } from "./frame/util/StringUtil";
import { TimeUtil } from "./frame/util/TimeUtil";
import { uint64 } from "./frame/util/uint64";
import { Callback } from "./game/event/Callback";
import { EventID } from "./game/event/EventID";
import { EventManager } from "./game/event/EventManager";
import { ClientSocket, SERVERTYPE } from "./game/network/ClientSocket";
import { Dictionary } from "./game/structure/Dictionary";

window['TimeUtil'] = TimeUtil;
window['Callback'] = Callback;
window['LogSys'] = LogSys;
window["ClientSocket"] = ClientSocket;
window['EventID'] = EventID;
window['uint64'] = uint64;
window['StringUtil'] = StringUtil;
window['RandomUtil'] = RandomUtil;
window['ListUtil'] = ListUtil;
window['SERVERTYPE'] = SERVERTYPE;
window['TimeCtl'] = TimeCtl;
window['DebugUtil'] = DebugUtil;
window['TimeCheckCtl'] = TimeCheckCtl;
window['EventManager'] = EventManager;
window['Dictionary'] = Dictionary;
window['ButtonCtl'] = ButtonCtl;
window['CheckBoxCtl'] = CheckBoxCtl;
window['TabControl'] = TabControl;
window['HttpUtil'] = HttpUtil;
window['LayoutUtil'] = LayoutUtil;